### ISSUE TITLE
Not getting inet6 addresses properly

### ISSUE THREAD

**Issue by muffeeee** [xinkaiwang/ifconfig-linux#1]
Running your example on a linux system that has an ipv6 address will only return the "scope: Link" address.

Expected output:
```
inet6: [ 
   { addr: 'fe80::601:5aff:fec5:201/64', scope: 'Link' },
   { addr: '2a03:d34d:b33f::5001/64', scope: 'Global' } 
]
```
Actual output: 
```
inet6: { addr: 'fe80::601:5aff:fec5:201/64', scope: 'Link' } 
```

I guess this package doesn't take into account that a device may have multiple inet addresses.

**Comment by xinkaiwang** [comment]
Thanks @muffeeee for bring this up. This is kind of limitation of current json schema. I'm unable to think of a good way to fix it without breaking existing dependency. so far the current code meet my need, so I would rather keep this code as it is. Can you share more about your needs maybe I can change with a major version bump up?

**Comment by muffeeee** [comment]
Well, in order to not break anything, you could just display the scope: global ipv6 address instead of the scope: link one, as it's likely that's what most people are looking for anyway :P
